/* creation script for table areas */
CREATE TABLE AREAS (
  NAME VARCHAR2(64 CHAR) NOT NULL, 
  CITY VARCHAR2(32 CHAR) NOT NULL, 
  A_LOC PUBLIC.SDO_GEOMETRY, 
  CONSTRAINT AREA_PK PRIMARY KEY (NAME, CITY) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
CREATE INDEX AREA_SPATIAL_IDX ON AREAS (A_LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;


/* creation script for table stations */
CREATE TABLE STATIONS (
  NAME VARCHAR2(32 CHAR) NOT NULL, 
  LINE_ID VARCHAR2(3 CHAR) NOT NULL, 
  S_LOC MDSYS.SDO_GEOMETRY, 
  CONSTRAINT STATIONS_PK PRIMARY KEY (NAME, LINE_ID) ENABLE
) LOGGING TABLESPACE "USERS" PCTFREE 10 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 BUFFER_POOL DEFAULT
);
CREATE INDEX STATIONS_SPATIAL_IDX ON STATIONS (S_LOC) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
